In [33]:
import numpy as np
from numpy import genfromtxt

In [34]:
data = genfromtxt('../DATA/bank_note_data.txt', delimiter=',')
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [35]:
#Split data to features and labels
features = data[:,0:4]
X = features
X

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [36]:
labels = data[:,4]
y = labels
y

array([0., 0., 0., ..., 1., 1., 1.])

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.33, random_state=42)

In [38]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [39]:
pip install keras --upgrade

Note: you may need to restart the kernel to use updated packages.


In [40]:
from keras.models import Sequential
from keras.layers import Dense

In [45]:
#1. Create the model
model = Sequential()

#Creare layers
model.add(Dense(4, input_dim = 4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

model.fit(scaled_X_train, y_train, epochs = 100, verbose = 2)

Epoch 1/100


/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


29/29 - 0s - 9ms/step - accuracy: 0.4505 - loss: 0.7665
Epoch 2/100
29/29 - 0s - 937us/step - accuracy: 0.4505 - loss: 0.7230
Epoch 3/100
29/29 - 0s - 946us/step - accuracy: 0.4385 - loss: 0.6978
Epoch 4/100
29/29 - 0s - 735us/step - accuracy: 0.6496 - loss: 0.6813
Epoch 5/100
29/29 - 0s - 704us/step - accuracy: 0.7378 - loss: 0.6695
Epoch 6/100
29/29 - 0s - 726us/step - accuracy: 0.6572 - loss: 0.6595
Epoch 7/100
29/29 - 0s - 714us/step - accuracy: 0.6866 - loss: 0.6495
Epoch 8/100
29/29 - 0s - 677us/step - accuracy: 0.6779 - loss: 0.6394
Epoch 9/100
29/29 - 0s - 700us/step - accuracy: 0.7106 - loss: 0.6283
Epoch 10/100
29/29 - 0s - 716us/step - accuracy: 0.7519 - loss: 0.6161
Epoch 11/100
29/29 - 0s - 733us/step - accuracy: 0.7737 - loss: 0.6025
Epoch 12/100
29/29 - 0s - 716us/step - accuracy: 0.8128 - loss: 0.5877
Epoch 13/100
29/29 - 0s - 766us/step - accuracy: 0.8466 - loss: 0.5712
Epoch 14/100
29/29 - 0s - 755us/step - accuracy: 0.8868 - loss: 0.5506
Epoch 15/100
29/29 - 0s - 1ms

In [46]:
#predict on test
from sklearn.metrics import confusion_matrix, classification_report
predictions = np.argmax(model.predict(scaled_X_test), axis=-1)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


In [47]:
confusion_matrix(y_test,predictions)

array([[257,   0],
       [196,   0]])

In [48]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.57      1.00      0.72       257
         1.0       0.00      0.00      0.00       196

    accuracy                           0.57       453
   macro avg       0.28      0.50      0.36       453
weighted avg       0.32      0.57      0.41       453



/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
