In [23]:
import torch
import numpy as np

In [24]:
# Scalar tensor
x = torch.tensor(5)
print(x)
print(x.size)
print(x.shape)
print(x.ndim)

tensor(5)
<built-in method size of Tensor object at 0x17f989f80>
torch.Size([])
0


In [25]:
# Vector tensor
x = torch.tensor([1,2,3,4])
print(x)
print(x.size)
print(x.shape)
print(x.ndim)

tensor([1, 2, 3, 4])
<built-in method size of Tensor object at 0x17fd882c0>
torch.Size([4])
1


In [26]:
# Matrix tensor
x = torch.tensor([[1,2,3], [4,5,6]])
print(x)
print(x.size)
print(x.shape)
print(x.ndim)

tensor([[1, 2, 3],
        [4, 5, 6]])
<built-in method size of Tensor object at 0x17fd88770>
torch.Size([2, 3])
2


In [27]:
# 3D tenosr
x = torch.rand(2, 3, 4)
print(x)
print(x.shape)
print(x.ndim)

tensor([[[0.9641, 0.0820, 0.0739, 0.3865],
         [0.2795, 0.6162, 0.4779, 0.3846],
         [0.1200, 0.9885, 0.5604, 0.3767]],

        [[0.8800, 0.4559, 0.3321, 0.6852],
         [0.0359, 0.4438, 0.1947, 0.2288],
         [0.5069, 0.1237, 0.6982, 0.1548]]])
torch.Size([2, 3, 4])
3


In [28]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [29]:
x = torch.from_numpy(x)
x

tensor([1, 2, 3, 4, 5])

In [30]:
#2D
x = np.arange(0,12)
x = x.reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
x = torch.from_numpy(x)
x

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [40]:
#Direct link
x = np.arange(1,12)
print(x)
tensor = torch.from_numpy(x)
print(tensor)

x[0] = 99
print(x)
print(tensor)

[ 1  2  3  4  5  6  7  8  9 10 11]
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
[99  2  3  4  5  6  7  8  9 10 11]
tensor([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [41]:
#To avoid direct link
x = np.arange(1,12)
print(x)
tensor = torch.tensor(x)
print(tensor)

x[0] = 99
print(x)
print(tensor)

[ 1  2  3  4  5  6  7  8  9 10 11]
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
[99  2  3  4  5  6  7  8  9 10 11]
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [47]:
#Create tensors in PyTorch
x = np.array([1,2,3])
print(f'It will create tensor from numpy and keep data type: {torch.tensor(x)}')
print(f'It will create tensor from numpy but will change data type to float: {torch.Tensor(x)}')


It will create tensor from numpy and keep data type: tensor([1, 2, 3])
It will create tensor from numpy but will change data type to float: tensor([1., 2., 3.])


In [51]:
#Torch zeros
x = torch.zeros(1,5,3)
x

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [54]:
#Torch ones 
x = torch.ones(4,1)
x

tensor([[1.],
        [1.],
        [1.],
        [1.]])

In [56]:
#Arange in PyTorch
x = torch.arange(0,18,2).reshape(3,3)
x

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [ ]:
#Tensor between 0 and 1
torch.rand(4,3)

tensor([[0.9645, 0.0600, 0.6026],
        [0.9831, 0.0426, 0.3648],
        [0.7896, 0.4165, 0.5060],
        [0.4606, 0.1910, 0.9065]])

In [ ]:
#Tensor with mean ) and std = 1
torch.randn(4,3)

tensor([[-0.9146, -0.0483, -0.7249],
        [-0.0476, -0.3205,  0.7906],
        [ 0.3617, -0.6314, -0.1912],
        [-0.1484,  1.4674, -0.2231]])

In [59]:
torch.randint(0,10,size=(10,10))

tensor([[7, 5, 3, 9, 2, 5, 9, 7, 1, 6],
        [7, 0, 5, 6, 3, 0, 4, 8, 1, 1],
        [3, 7, 2, 6, 6, 9, 0, 8, 8, 8],
        [7, 0, 1, 9, 4, 4, 5, 1, 4, 9],
        [2, 0, 3, 9, 2, 0, 5, 3, 2, 2],
        [0, 5, 8, 4, 8, 6, 1, 0, 1, 2],
        [8, 5, 8, 0, 7, 9, 7, 5, 5, 2],
        [6, 7, 2, 9, 8, 5, 7, 0, 1, 5],
        [7, 1, 2, 5, 3, 6, 6, 1, 1, 0],
        [9, 9, 2, 5, 5, 8, 7, 8, 0, 3]])

In [66]:
#Manual seed to keep same values always
torch.manual_seed(42) #alwyas use it in the beggining if you know you want to keep same vlaues
print(torch.rand(2,3))
torch.manual_seed(42)
print(torch.rand(2,3))
torch.manual_seed(42)
print(torch.rand(2,3))

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [64]:
#Without manual_seed it will be different
print(torch.rand(2,3))
print(torch.rand(2,3))
print(torch.rand(2,3))

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])
tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])
tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])
