In [17]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
#Introduction to tensors

#Scalar tensor
a = torch.tensor(7)
print(f'Scalar tensor {a}')

#Get tensor back as Python int
a = a.item()
print(f'Back as Python int {a}')


Scalar tensor 7
Back as Python int 7


In [19]:
print(a)

7


In [20]:
#Vector
vector = torch.tensor([7,7])
vector.ndim

1

In [22]:
print(vector)

tensor([7, 7])


In [ ]:
#Matrix
matrix = torch.tensor([[7, 8], [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
#Tensor
tensor = torch.tensor([[[1,2,3], 
                        [3,6,7],
                        [8,9,10]]])
tensor

tensor([[[ 1,  2,  3],
         [ 3,  6,  7],
         [ 8,  9, 10]]])

In [25]:
#Random Tensors of size/shape (3,4)

x = torch.rand(3,4)
x


tensor([[0.6090, 0.8460, 0.4564, 0.2536],
        [0.9367, 0.2170, 0.0938, 0.0460],
        [0.7706, 0.1541, 0.2646, 0.4113]])

In [26]:
x.ndim

2

In [27]:
y = torch.rand(100,100)
y

tensor([[0.9225, 0.6213, 0.4633,  ..., 0.6774, 0.9561, 0.3283],
        [0.2348, 0.5079, 0.5616,  ..., 0.2352, 0.2875, 0.4439],
        [0.5280, 0.2125, 0.0148,  ..., 0.3695, 0.5563, 0.0226],
        ...,
        [0.4219, 0.3584, 0.3070,  ..., 0.3147, 0.0595, 0.7536],
        [0.7086, 0.4461, 0.0079,  ..., 0.8673, 0.8512, 0.3782],
        [0.9858, 0.6079, 0.2148,  ..., 0.5466, 0.7712, 0.3302]])

In [29]:
#Zeros and ones
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
ones = torch.ones(6,10,10)
ones

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.,

In [34]:
#Tensors range
x = torch.arange(0, 10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#Step
x = torch.arange(0,100, step = 25)
x

tensor([ 0, 25, 50, 75])

In [38]:
#Tensors like
x_like = torch.zeros_like(x)
x_like

tensor([0, 0, 0, 0])

In [ ]:
#Tensors data types
