In [17]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
#Introduction to tensors

#Scalar tensor
a = torch.tensor(7)
print(f'Scalar tensor {a}')

#Get tensor back as Python int
a = a.item()
print(f'Back as Python int {a}')


Scalar tensor 7
Back as Python int 7


In [19]:
print(a)

7


In [20]:
#Vector
vector = torch.tensor([7,7])
vector.ndim

1

In [22]:
print(vector)

tensor([7, 7])


In [ ]:
#Matrix
matrix = torch.tensor([[7, 8], [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
#Tensor
tensor = torch.tensor([[[1,2,3], 
                        [3,6,7],
                        [8,9,10]]])
tensor

tensor([[[ 1,  2,  3],
         [ 3,  6,  7],
         [ 8,  9, 10]]])

In [25]:
#Random Tensors of size/shape (3,4)

x = torch.rand(3,4)
x


tensor([[0.6090, 0.8460, 0.4564, 0.2536],
        [0.9367, 0.2170, 0.0938, 0.0460],
        [0.7706, 0.1541, 0.2646, 0.4113]])

In [26]:
x.ndim

2

In [27]:
y = torch.rand(100,100)
y

tensor([[0.9225, 0.6213, 0.4633,  ..., 0.6774, 0.9561, 0.3283],
        [0.2348, 0.5079, 0.5616,  ..., 0.2352, 0.2875, 0.4439],
        [0.5280, 0.2125, 0.0148,  ..., 0.3695, 0.5563, 0.0226],
        ...,
        [0.4219, 0.3584, 0.3070,  ..., 0.3147, 0.0595, 0.7536],
        [0.7086, 0.4461, 0.0079,  ..., 0.8673, 0.8512, 0.3782],
        [0.9858, 0.6079, 0.2148,  ..., 0.5466, 0.7712, 0.3302]])

In [29]:
#Zeros and ones
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
ones = torch.ones(6,10,10)
ones

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.,

In [34]:
#Tensors range
x = torch.arange(0, 10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
#Step
x = torch.arange(0,100, step = 25)
x

tensor([ 0, 25, 50, 75])

In [38]:
#Tensors like
x_like = torch.zeros_like(x)
x_like

tensor([0, 0, 0, 0])

In [40]:
#Tensors data types
tensor_float32 = torch.tensor([1.,2.,3.])
tensor_float32.dtype

torch.float32

In [47]:
#Change float32 to float16
tensor_float32 = torch.tensor(tensor_float32, dtype=torch.float16)
tensor_float32.dtype

/var/folders/bj/p18ygv1s6wbg6865d00fd5h80000gn/T/ipykernel_15436/2324419800.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor_float32 = torch.tensor(tensor_float32, dtype=torch.float16)


torch.float16

In [51]:
#Basic computing
tensor_16 = torch.tensor([1,2,3], dtype=torch.float16)
tensor_32 = torch.tensor([4,5,6], dtype=torch.float32)

result = tensor_16 * tensor_32
print(result)
print(f'Result dtype is {result.dtype}')


tensor([ 4., 10., 18.])
Result dtype is torch.float32


In [54]:
#Getting info from tensor
tensor = torch.rand(3,5)
tensor

tensor([[0.7158, 0.0934, 0.7011, 0.0048, 0.4863],
        [0.1899, 0.6904, 0.5085, 0.7890, 0.2211],
        [0.3364, 0.4023, 0.4517, 0.6735, 0.7790]])

In [55]:
print(f'Tensor dtype {tensor.dtype}')
print(f'Tensor device {tensor.device}')
print(f'Tensor shape {tensor.shape}')

Tensor dtype torch.float32
Tensor device cpu
Tensor shape torch.Size([3, 5])


In [ ]:
#Manipulating tensors
tensor = torch.tensor([1,2,3])

In [84]:
#Addition
plus_10_tensor = tensor + 10
plus_10_tensor

tensor([11, 12, 13])

In [85]:
#Substraction
minus_10_tensor = tensor - 10
minus_10_tensor

tensor([-9, -8, -7])

In [86]:
#Multiplication
x10_tensor = tensor * 10
x10_tensor

tensor([10, 20, 30])

In [89]:
#Divided
divided_10_tensor = tensor / 10
divided_10_tensor

tensor([0.1000, 0.2000, 0.3000])

In [93]:
#PyTourch functions
mul_tensor = torch.mul(tensor, 10)
print(f'Multiplication: {mul_tensor}')

add_tensor = torch.add(tensor, 10)
print(f'Add tensor {add_tensor}')
 

Multiplication: tensor([10, 20, 30])
Add tensor tensor([11, 12, 13])


In [98]:
#Matrix multiplication
tensor = torch.tensor([1,2,3])

print(tensor * tensor)

#Matmul
result = torch.matmul(tensor, tensor)
print(result)

tensor([1, 4, 9])
tensor(14)


In [101]:
%%time
value = 0 

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 617 μs, sys: 617 μs, total: 1.23 ms
Wall time: 873 μs


In [102]:
%%time
result = torch.matmul(tensor, tensor)
print(result)

tensor(14)
CPU times: user 425 μs, sys: 200 μs, total: 625 μs
Wall time: 458 μs


### Matrix multiplication (is all you need)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) method.

The main two rules for matrix multiplication to remember are:

1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **Note:** "`@`" in Python is the symbol for matrix multiplication.

> **Resource:** You can see all of the rules for matrix multiplication using `torch.matmul()` [in the PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.matmul.html).


In [118]:
big_tensor = torch.rand(150,100)
big_tensor_2 = torch.rand(100, 150)

In [121]:
res = torch.matmul(big_tensor, big_tensor_2)
print(res)

tensor([[20.9393, 22.5982, 24.7351,  ..., 24.0779, 23.1439, 24.4342],
        [23.4283, 26.7501, 28.7740,  ..., 27.9573, 25.7744, 28.3308],
        [19.9308, 22.3116, 23.1577,  ..., 24.2011, 21.8323, 23.4926],
        ...,
        [22.7281, 22.1666, 25.9965,  ..., 25.9288, 24.4183, 24.6909],
        [23.1253, 22.6344, 25.0351,  ..., 26.0116, 24.8118, 25.8436],
        [20.6604, 22.6575, 24.1706,  ..., 24.1706, 23.0397, 25.2060]])


In [127]:
#Transpose can change the shape of tensor so it can conduct the multiplication. If not use it ill print shape error because of shape of tensors (2,1: 2,1)
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

result = torch.mm(tensor_a, tensor_b.T)
print(result)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
