In [62]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [63]:
#Introduction to tensors

#Scalar tensor
a = torch.tensor(7)
print(f'Scalar tensor {a}')

#Get tensor back as Python int
a = a.item()
print(f'Back as Python int {a}')


Scalar tensor 7
Back as Python int 7


In [64]:
print(a)

7


In [65]:
#Vector
vector = torch.tensor([7,7])
vector.ndim

1

In [66]:
print(vector)

tensor([7, 7])


In [67]:
#Matrix
matrix = torch.tensor([[7, 8], [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [68]:
#Tensor
tensor = torch.tensor([[[1,2,3], 
                        [3,6,7],
                        [8,9,10]]])
tensor

tensor([[[ 1,  2,  3],
         [ 3,  6,  7],
         [ 8,  9, 10]]])

In [69]:
#Random Tensors of size/shape (3,4)

x = torch.rand(3,4)
x


tensor([[0.3340, 0.5204, 0.6282, 0.7763],
        [0.5479, 0.9109, 0.9022, 0.5344],
        [0.3792, 0.4980, 0.1730, 0.3699]])

In [70]:
x.ndim

2

In [71]:
y = torch.rand(100,100)
y

tensor([[0.7919, 0.8112, 0.8438,  ..., 0.2636, 0.1914, 0.3407],
        [0.4856, 0.5260, 0.1407,  ..., 0.4536, 0.3259, 0.3948],
        [0.2144, 0.5835, 0.7544,  ..., 0.7963, 0.2443, 0.3112],
        ...,
        [0.9200, 0.9310, 0.1640,  ..., 0.1771, 0.3419, 0.1653],
        [0.4563, 0.1734, 0.9139,  ..., 0.5638, 0.1424, 0.9826],
        [0.3029, 0.2711, 0.8679,  ..., 0.8126, 0.8273, 0.0741]])

In [72]:
#Zeros and ones
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [73]:
ones = torch.ones(6,10,10)
ones

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.,

In [74]:
#Tensors range
x = torch.arange(0, 10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
#Step
x = torch.arange(0,100, step = 25)
x

tensor([ 0, 25, 50, 75])

In [76]:
#Tensors like
x_like = torch.zeros_like(x)
x_like

tensor([0, 0, 0, 0])

In [77]:
#Tensors data types
tensor_float32 = torch.tensor([1.,2.,3.])
tensor_float32.dtype

torch.float32

In [78]:
#Change float32 to float16
tensor_float32 = torch.tensor(tensor_float32, dtype=torch.float16)
tensor_float32.dtype

/var/folders/bj/p18ygv1s6wbg6865d00fd5h80000gn/T/ipykernel_1726/2324419800.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor_float32 = torch.tensor(tensor_float32, dtype=torch.float16)


torch.float16

In [79]:
#Basic computing
tensor_16 = torch.tensor([1,2,3], dtype=torch.float16)
tensor_32 = torch.tensor([4,5,6], dtype=torch.float32)

result = tensor_16 * tensor_32
print(result)
print(f'Result dtype is {result.dtype}')


tensor([ 4., 10., 18.])
Result dtype is torch.float32


In [80]:
#Getting info from tensor
tensor = torch.rand(3,5)
tensor

tensor([[0.2060, 0.8282, 0.3784, 0.6042, 0.2850],
        [0.5987, 0.8030, 0.4543, 0.4906, 0.3000],
        [0.7858, 0.6516, 0.9579, 0.1610, 0.4129]])

In [81]:
print(f'Tensor dtype {tensor.dtype}')
print(f'Tensor device {tensor.device}')
print(f'Tensor shape {tensor.shape}')

Tensor dtype torch.float32
Tensor device cpu
Tensor shape torch.Size([3, 5])


In [82]:
#Manipulating tensors
tensor = torch.tensor([1,2,3])

In [83]:
#Addition
plus_10_tensor = tensor + 10
plus_10_tensor

tensor([11, 12, 13])

In [84]:
#Substraction
minus_10_tensor = tensor - 10
minus_10_tensor

tensor([-9, -8, -7])

In [85]:
#Multiplication
x10_tensor = tensor * 10
x10_tensor

tensor([10, 20, 30])

In [86]:
#Divided
divided_10_tensor = tensor / 10
divided_10_tensor

tensor([0.1000, 0.2000, 0.3000])

In [87]:
#PyTourch functions
mul_tensor = torch.mul(tensor, 10)
print(f'Multiplication: {mul_tensor}')

add_tensor = torch.add(tensor, 10)
print(f'Add tensor {add_tensor}')
 

Multiplication: tensor([10, 20, 30])
Add tensor tensor([11, 12, 13])


In [88]:
#Matrix multiplication
tensor = torch.tensor([1,2,3])

print(tensor * tensor)

#Matmul
result = torch.matmul(tensor, tensor)
print(result)

tensor([1, 4, 9])
tensor(14)


In [89]:
%%time
value = 0 

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 342 μs, sys: 376 μs, total: 718 μs
Wall time: 468 μs


In [90]:
%%time
result = torch.matmul(tensor, tensor)
print(result)

tensor(14)
CPU times: user 238 μs, sys: 125 μs, total: 363 μs
Wall time: 270 μs


### Matrix multiplication (is all you need)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) method.

The main two rules for matrix multiplication to remember are:

1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **Note:** "`@`" in Python is the symbol for matrix multiplication.

> **Resource:** You can see all of the rules for matrix multiplication using `torch.matmul()` [in the PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.matmul.html).


In [91]:
big_tensor = torch.rand(150,100)
big_tensor_2 = torch.rand(100, 150)

In [92]:
res = torch.matmul(big_tensor, big_tensor_2)
print(res)

tensor([[25.7632, 23.7852, 26.5929,  ..., 24.3361, 23.8048, 26.2316],
        [26.8485, 25.1185, 26.9575,  ..., 25.7474, 25.0357, 26.2415],
        [25.0396, 24.7508, 26.2407,  ..., 24.7117, 23.5138, 26.0816],
        ...,
        [25.2057, 23.4811, 24.8952,  ..., 23.0419, 22.5479, 25.8658],
        [27.5301, 25.5140, 24.2050,  ..., 26.3588, 25.0366, 26.2375],
        [23.1176, 22.9114, 25.0165,  ..., 22.5208, 21.2752, 23.2787]])


In [93]:
#Transpose can change the shape of tensor so it can conduct the multiplication. If not use it ill print shape error because of shape of tensors (2,1: 2,1)
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

result = torch.mm(tensor_a, tensor_b.T)
print(result)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])


In [94]:
#Min, Max
tensor = torch.arange(0,100,10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [95]:
torch.min(tensor)

tensor(0)

In [96]:
torch.max(tensor)

tensor(90)

In [97]:
#Rememebrt o change to float
torch.mean(tensor.type(torch.float32))

tensor(45.)

In [98]:
#Positional Min and Max
print(f'Positional min: {tensor.argmin()}')
print(f'Positional max: {tensor.argmax()}')

Positional min: 0
Positional max: 9


### Reshaping, stacking, squeezing and unsqueezing


| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. | 

Deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors. 

In [99]:
x = torch.arange(1.,10,)
x.shape

torch.Size([9])

In [100]:
#Add dimension
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [101]:
x = torch.arange(1,11)
x_reshaped = x.reshape(5,2)
x_reshaped

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [102]:
#Stack tensors
x_stack = torch.stack([x,x,x,x,x,x,x,x], dim=1)
x_stack


tensor([[ 1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,  5,  5,  5,  5,  5,  5,  5],
        [ 6,  6,  6,  6,  6,  6,  6,  6],
        [ 7,  7,  7,  7,  7,  7,  7,  7],
        [ 8,  8,  8,  8,  8,  8,  8,  8],
        [ 9,  9,  9,  9,  9,  9,  9,  9],
        [10, 10, 10, 10, 10, 10, 10, 10]])

In [112]:
x_stack = torch.stack([x,x,x,x,x,x,x,x], dim=1)
x_stack.shape

torch.Size([10, 8])

In [119]:
x_reshaped

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [123]:
#Squeeze, will squeeze remove all single dimensions
x = torch.arange(1., 8.)
x_reshaped = x.reshape(1, 7)
x_reshaped


tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [124]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([1., 2., 3., 4., 5., 6., 7.])

In [129]:
#Unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [ ]:
#Torch.permute reaarenges dimension of target tensor in specified order
x = torch.randn(2, 3, 5)
print(x.size())
torch.permute(x, (2, 0, 1)).size()

torch.Size([2, 3, 5])


torch.Size([5, 2, 3])

In [135]:
#Indexing
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [142]:
x[0][0]

tensor([1, 2, 3])

In [143]:
x[0][0][0]

tensor(1)

In [144]:
x[0][0][2]

tensor(3)

In [145]:
#Pick 5
x[0][1][1]

tensor(5)

In [146]:
#Pirck 7
x[0][2][0]

tensor(7)

In [147]:
#Pick 9
x[0][2][2]

tensor(9)

In [149]:
#PyTorch and Numpy
import numpy as np

array = np.arange(1.,8.)
tensor = torch.from_numpy(array)
print(array)
print(tensor)

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [157]:
#Random seed keeps the value in tensors!
RANDOM_SEED=987654
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_A = torch.rand(3, 4)

torch.random.manual_seed(seed=RANDOM_SEED) 
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2123, 0.5460, 0.4346, 0.2198],
        [0.9480, 0.7973, 0.0518, 0.1570],
        [0.8100, 0.2804, 0.0313, 0.7250]])

Tensor B:
tensor([[0.2123, 0.5460, 0.4346, 0.2198],
        [0.9480, 0.7973, 0.0518, 0.1570],
        [0.8100, 0.2804, 0.0313, 0.7250]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [159]:
#GPU or Apple check
torch.cuda.is_available()

False

In [160]:
torch.mps.is_available()

True

In [161]:
device = 'cuda' if torch.cuda.is_available() else 'mps'
device

'mps'

In [166]:
#Put tenosrs and model on mps
tensor = torch.arange(1,10,1)
tensor_on_mps = tensor.to(device)
tensor_on_mps

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], device='mps:0')

In [168]:
#1. Create tensor 7x7
tensor = torch.rand(7,7)
tensor.size()

torch.Size([7, 7])

In [178]:
#2. Matrix multiplications
tensor_b = torch.rand(1,7)


res = torch.mm(tensor, tensor_b.T)
res

tensor([[1.6838],
        [1.9499],
        [1.8029],
        [3.1500],
        [1.3352],
        [2.1484],
        [1.9877]])

In [181]:
#3. Random seed
RANDOM_SEED = 0

torch.manual_seed(seed=RANDOM_SEED)
tensor = torch.rand(7,7)

torch.manual_seed(seed=RANDOM_SEED)
tensor_b = torch.rand(1,7)

res = torch.mm(tensor, tensor_b.T)
res

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [189]:
#4. Tensor to MPS
tensor_a = torch.rand(2,3, device='mps')
tensor_b = torch.rand(2,3, device='mps')

res = torch.mm(tensor_a, tensor_b.T)
res

tensor([[0.3642, 0.2782],
        [0.7305, 0.3835]], device='mps:0')

In [191]:
#5. Min, Max values
print(res.min())
print(res.max())

tensor(0.2782, device='mps:0')
tensor(0.7305, device='mps:0')
