In [1]:
import torch
import numpy as np

In [2]:
#Indexing and slicing
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [7]:
print(x[1,0])
print(x[0,1])
print(x[2,1])
print(x[1,1])

tensor(2)
tensor(1)
tensor(5)
tensor(3)


In [ ]:
print(x[:,1])
print(x[:,0])

tensor([1, 3, 5])
tensor([0, 2, 4])
tensor([1, 3, 5])


In [10]:
print(x[0,:])
print(x[1,:])
print(x[2,:])

tensor([0, 1])
tensor([2, 3])
tensor([4, 5])


In [11]:
#View and reshape
x = torch.arange(10)
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#View and reshape
x = torch.arange(6).reshape(2,3)
print(x)
x = x.t()
print(x)


tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 3],
        [1, 4],
        [2, 5]])


tensor([0, 3, 1, 4, 2, 5])