In [59]:
import torch
import numpy as np
import random

In [60]:
np.random.seed(42)
torch.manual_seed(42)

In [61]:
arr = np.random.randint(0,6, size=6)
arr

array([3, 4, 2, 4, 4, 1])

In [62]:
x = torch.from_numpy(arr)
x

tensor([3, 4, 2, 4, 4, 1])

In [63]:
x = torch.reshape(x, shape=(3,2))
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

In [64]:
x[:,1:]

tensor([[4],
        [4],
        [1]])

In [70]:
x**2

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [66]:
y = torch.randint(low=0, high=6, size=(2,3))
y

tensor([[0, 5, 4],
        [4, 0, 5]])

In [67]:
print(x.size())
print(y.size())

torch.Size([3, 2])
torch.Size([2, 3])


In [68]:
torch.matmul(x,y)

tensor([[16, 15, 32],
        [16, 10, 28],
        [ 4, 20, 21]])

In [69]:
x @ y

tensor([[16, 15, 32],
        [16, 10, 28],
        [ 4, 20, 21]])