In [37]:
import torch
import numpy as np
import random

In [38]:
torch.manual_seed(42)

In [39]:
arr = np.random.randint(0,6, size=6)
arr

array([2, 1, 2, 3, 1, 4])

In [40]:
x = torch.from_numpy(arr)
x

tensor([2, 1, 2, 3, 1, 4])

In [41]:
x = torch.reshape(x, shape=(3,2))
x

tensor([[2, 1],
        [2, 3],
        [1, 4]])

In [42]:
x[:,1:]

tensor([[1],
        [3],
        [4]])

In [44]:
x[:,1:]**2

tensor([[ 1],
        [ 9],
        [16]])

In [46]:
y = torch.randint(low=0, high=6, size=(2,3))
y

tensor([[0, 5, 4],
        [4, 0, 5]])

In [49]:
print(x.size())
print(y.size())

torch.Size([3, 2])
torch.Size([2, 3])


In [54]:
torch.matmul(x,y)

tensor([[ 4, 10, 13],
        [12, 10, 23],
        [16,  5, 24]])

In [52]:
x @ y

tensor([[ 4, 10, 13],
        [12, 10, 23],
        [16,  5, 24]])