In [28]:
import torch
import numpy as np

In [29]:
#Indexing and slicing
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [30]:
print(x[1,0])
print(x[0,1])
print(x[2,1])
print(x[1,1])

tensor(2)
tensor(1)
tensor(5)
tensor(3)


In [31]:
print(x[:,1])
print(x[:,0])

tensor([1, 3, 5])
tensor([0, 2, 4])


In [32]:
print(x[0,:])
print(x[1,:])
print(x[2,:])

tensor([0, 1])
tensor([2, 3])
tensor([4, 5])


In [33]:
#View and reshape
x = torch.arange(10)
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [34]:
#View and reshape
x = torch.arange(6).reshape(2,3)
print(x)
x = x.t()
print(x)


tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [35]:
#Arithmetics
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
print(a)
print(b)


tensor([1, 2, 3])
tensor([4, 5, 6])


In [36]:
a + b

tensor([5, 7, 9])

In [37]:
a - b

tensor([-3, -3, -3])

In [39]:
#Mul
a.mul_(b)

tensor([ 4, 10, 18])