In [1]:
import numpy as np 

In [4]:
#Crash course
my_list = [1,2,3,4,5,6]
type(my_list)

list

In [6]:
#Create the list from _ to _ with step by every choosen number
np.arange(0,900,12)

array([  0,  12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144,
       156, 168, 180, 192, 204, 216, 228, 240, 252, 264, 276, 288, 300,
       312, 324, 336, 348, 360, 372, 384, 396, 408, 420, 432, 444, 456,
       468, 480, 492, 504, 516, 528, 540, 552, 564, 576, 588, 600, 612,
       624, 636, 648, 660, 672, 684, 696, 708, 720, 732, 744, 756, 768,
       780, 792, 804, 816, 828, 840, 852, 864, 876, 888])

In [10]:
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
#Random numbers
random_num = np.random.randint(1,100,10)
random_num

array([91, 65, 62, 10, 24, 89, 90, 64, 40,  5])

In [15]:
random_num.max()

91

In [16]:
random_num.mean()

54.0

In [17]:
random_num.min()

5

In [18]:
random_num.std()

30.996774025694997

In [22]:
len(random_num)

10