In [2]:
import numpy as np 

In [3]:
#Crash course
my_list = [1,2,3,4,5,6]
type(my_list)

list

In [4]:
#Create the list from _ to _ with step by every choosen number
np.arange(0,900,12)

array([  0,  12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144,
       156, 168, 180, 192, 204, 216, 228, 240, 252, 264, 276, 288, 300,
       312, 324, 336, 348, 360, 372, 384, 396, 408, 420, 432, 444, 456,
       468, 480, 492, 504, 516, 528, 540, 552, 564, 576, 588, 600, 612,
       624, 636, 648, 660, 672, 684, 696, 708, 720, 732, 744, 756, 768,
       780, 792, 804, 816, 828, 840, 852, 864, 876, 888])

In [5]:
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
#Random numbers
random_num = np.random.randint(1,100,10)
random_num

array([25, 55,  4, 76, 67, 55, 60, 50, 11, 16])

In [7]:
random_num.max()

76

In [8]:
random_num.mean()

41.9

In [9]:
random_num.min()

4

In [10]:
random_num.std()

24.24231837098094

In [11]:
len(random_num)

10

In [14]:
arr = np.ones((10,10))
arr*10

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])